# Generated by Django 4.0.3 on 2022-06-18 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0004_remove_friendlist_friend_list_friendlist_friend_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friend_list',
            field=models.ManyToManyField(blank=True, related_name='friend_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='list_of',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='list_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
