# Generated by Django 4.0.3 on 2022-07-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprofile',
            name='image',
            field=models.ImageField(upload_to='images/profile/'),
        ),
    ]
