# Generated by Django 4.0.3 on 2022-05-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_dialog_user1_dialog_user2_message_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='user1',
            field=models.CharField(default='user1', max_length=20),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='user2',
            field=models.CharField(default='user2', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(default='author', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(default='content', max_length=290),
        ),
    ]
